### PR TITLE
Usage of ACM certificate instead of CloudFront

### PR DESCRIPTION
**Pull request by 3h4x**

### CODE REVIEW

**Comment by ofhouse** [comment]
Hi, the changes proposed in your are too opinionated:
- The CloudFront distribution would only work with custom domains
- The CloudFront distribution would only work with custom certificates

Adding these settings as optional parameters would work, but we don't want to force our users into using a custom domain.

**Comment by 3h4x** [comment]
> Hi, the changes proposed in your PR are too opinionated:
> 
> * The CloudFront distribution would only work with custom domains
> * The CloudFront distribution would only work with custom certificates
> 
> Adding these settings as optional parameters would work, but we don't want to force our users into using a custom domain.

I totally agree. Unfortunately I dont have time to improve it.
I thought to push PR and even if it gets rejected it will leave a trace so other people could eventually pick it up.

**Comment by ofhouse** [comment]
@3h4x Thanks for clarifying!
Will try to pick this up for one of the next releases.

**Comment by ofhouse** [comment]
This has been released in [`v12.1.3`](https://github.com/milliHQ/terraform-aws-next-js-image-optimization/releases/tag/v12.1.3). Thanks for contributing!

**Pull request merged**
